// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");

function pathJoin(dir_path, $$package) {
  return Path.join(dir_path, $$package).replace("/", Path.sep);
}

exports.pathJoin = pathJoin;
/* path Not a pure module */
