// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

var PathJoin = require("@knit/path-join/lib/js/pathJoin.js");
var ReadPkg  = require("read-pkg");

function readPkg(dir_path, $$package) {
  ReadPkg.sync(PathJoin.pathJoin(dir_path, $$package), /* record */[/* normalize : false */0]);
  return /* () */0;
}

exports.readPkg = readPkg;
/* PathJoin Not a pure module */
