// flow-typed signature: 8b0fe82eb966e0a4f91f618c0ad6c978
// flow-typed version: <<STUB>>/babel-plugin-array-includes_v2.0.3/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-array-includes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-array-includes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-array-includes/lib' {
  declare module.exports: any;
}

declare module 'babel-plugin-array-includes/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-array-includes/lib/index' {
  declare module.exports: $Exports<'babel-plugin-array-includes/lib'>;
}
declare module 'babel-plugin-array-includes/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-array-includes/lib'>;
}
declare module 'babel-plugin-array-includes/test/test.js' {
  declare module.exports: $Exports<'babel-plugin-array-includes/test/test'>;
}
