// flow-typed signature: 4610fc373659c498ab74adf8adc57ea5
// flow-typed version: <<STUB>>/babel-relay-plugin_v^0.9.3/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-relay-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-relay-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-relay-plugin/lib/babelAdapter' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/computeLocation' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/find' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/getBabelRelayPlugin' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/GraphQL' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/GraphQLRelayDirective' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/invariant' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/RelayQLAST' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/RelayQLNodeInterface' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/RelayQLPrinter' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/RelayQLTransformer' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/RelayTransformError' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/tools/generateSchemaJson' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/tools/readFixtures' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/tools/regenerateFixtures' {
  declare module.exports: any;
}

declare module 'babel-relay-plugin/lib/tools/transformGraphQL' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-relay-plugin/lib/babelAdapter.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/babelAdapter'>;
}
declare module 'babel-relay-plugin/lib/computeLocation.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/computeLocation'>;
}
declare module 'babel-relay-plugin/lib/find.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/find'>;
}
declare module 'babel-relay-plugin/lib/getBabelRelayPlugin.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/getBabelRelayPlugin'>;
}
declare module 'babel-relay-plugin/lib/GraphQL.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/GraphQL'>;
}
declare module 'babel-relay-plugin/lib/GraphQLRelayDirective.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/GraphQLRelayDirective'>;
}
declare module 'babel-relay-plugin/lib/invariant.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/invariant'>;
}
declare module 'babel-relay-plugin/lib/RelayQLAST.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/RelayQLAST'>;
}
declare module 'babel-relay-plugin/lib/RelayQLNodeInterface.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/RelayQLNodeInterface'>;
}
declare module 'babel-relay-plugin/lib/RelayQLPrinter.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/RelayQLPrinter'>;
}
declare module 'babel-relay-plugin/lib/RelayQLTransformer.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/RelayQLTransformer'>;
}
declare module 'babel-relay-plugin/lib/RelayTransformError.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/RelayTransformError'>;
}
declare module 'babel-relay-plugin/lib/tools/generateSchemaJson.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/tools/generateSchemaJson'>;
}
declare module 'babel-relay-plugin/lib/tools/readFixtures.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/tools/readFixtures'>;
}
declare module 'babel-relay-plugin/lib/tools/regenerateFixtures.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/tools/regenerateFixtures'>;
}
declare module 'babel-relay-plugin/lib/tools/transformGraphQL.js' {
  declare module.exports: $Exports<'babel-relay-plugin/lib/tools/transformGraphQL'>;
}
