// flow-typed signature: b8602925170a2fe952692c2cde16a198
// flow-typed version: <<STUB>>/babylon_v6.13.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babylon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babylon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babylon/bin/babylon' {
  declare module.exports: any;
}

declare module 'babylon/bin/generate-identifier-regex' {
  declare module.exports: any;
}

declare module 'babylon/lib/index' {
  declare module.exports: any;
}

declare module 'babylon/lib/options' {
  declare module.exports: any;
}

declare module 'babylon/lib/parser/comments' {
  declare module.exports: any;
}

declare module 'babylon/lib/parser/expression' {
  declare module.exports: any;
}

declare module 'babylon/lib/parser/index' {
  declare module.exports: any;
}

declare module 'babylon/lib/parser/location' {
  declare module.exports: any;
}

declare module 'babylon/lib/parser/lval' {
  declare module.exports: any;
}

declare module 'babylon/lib/parser/node' {
  declare module.exports: any;
}

declare module 'babylon/lib/parser/statement' {
  declare module.exports: any;
}

declare module 'babylon/lib/parser/util' {
  declare module.exports: any;
}

declare module 'babylon/lib/plugins/flow' {
  declare module.exports: any;
}

declare module 'babylon/lib/plugins/jsx/index' {
  declare module.exports: any;
}

declare module 'babylon/lib/plugins/jsx/xhtml' {
  declare module.exports: any;
}

declare module 'babylon/lib/tokenizer/context' {
  declare module.exports: any;
}

declare module 'babylon/lib/tokenizer/index' {
  declare module.exports: any;
}

declare module 'babylon/lib/tokenizer/state' {
  declare module.exports: any;
}

declare module 'babylon/lib/tokenizer/types' {
  declare module.exports: any;
}

declare module 'babylon/lib/util/identifier' {
  declare module.exports: any;
}

declare module 'babylon/lib/util/location' {
  declare module.exports: any;
}

declare module 'babylon/lib/util/whitespace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babylon/bin/babylon.js' {
  declare module.exports: $Exports<'babylon/bin/babylon'>;
}
declare module 'babylon/bin/generate-identifier-regex.js' {
  declare module.exports: $Exports<'babylon/bin/generate-identifier-regex'>;
}
declare module 'babylon/lib/index.js' {
  declare module.exports: $Exports<'babylon/lib/index'>;
}
declare module 'babylon/lib/options.js' {
  declare module.exports: $Exports<'babylon/lib/options'>;
}
declare module 'babylon/lib/parser/comments.js' {
  declare module.exports: $Exports<'babylon/lib/parser/comments'>;
}
declare module 'babylon/lib/parser/expression.js' {
  declare module.exports: $Exports<'babylon/lib/parser/expression'>;
}
declare module 'babylon/lib/parser/index.js' {
  declare module.exports: $Exports<'babylon/lib/parser/index'>;
}
declare module 'babylon/lib/parser/location.js' {
  declare module.exports: $Exports<'babylon/lib/parser/location'>;
}
declare module 'babylon/lib/parser/lval.js' {
  declare module.exports: $Exports<'babylon/lib/parser/lval'>;
}
declare module 'babylon/lib/parser/node.js' {
  declare module.exports: $Exports<'babylon/lib/parser/node'>;
}
declare module 'babylon/lib/parser/statement.js' {
  declare module.exports: $Exports<'babylon/lib/parser/statement'>;
}
declare module 'babylon/lib/parser/util.js' {
  declare module.exports: $Exports<'babylon/lib/parser/util'>;
}
declare module 'babylon/lib/plugins/flow.js' {
  declare module.exports: $Exports<'babylon/lib/plugins/flow'>;
}
declare module 'babylon/lib/plugins/jsx/index.js' {
  declare module.exports: $Exports<'babylon/lib/plugins/jsx/index'>;
}
declare module 'babylon/lib/plugins/jsx/xhtml.js' {
  declare module.exports: $Exports<'babylon/lib/plugins/jsx/xhtml'>;
}
declare module 'babylon/lib/tokenizer/context.js' {
  declare module.exports: $Exports<'babylon/lib/tokenizer/context'>;
}
declare module 'babylon/lib/tokenizer/index.js' {
  declare module.exports: $Exports<'babylon/lib/tokenizer/index'>;
}
declare module 'babylon/lib/tokenizer/state.js' {
  declare module.exports: $Exports<'babylon/lib/tokenizer/state'>;
}
declare module 'babylon/lib/tokenizer/types.js' {
  declare module.exports: $Exports<'babylon/lib/tokenizer/types'>;
}
declare module 'babylon/lib/util/identifier.js' {
  declare module.exports: $Exports<'babylon/lib/util/identifier'>;
}
declare module 'babylon/lib/util/location.js' {
  declare module.exports: $Exports<'babylon/lib/util/location'>;
}
declare module 'babylon/lib/util/whitespace.js' {
  declare module.exports: $Exports<'babylon/lib/util/whitespace'>;
}
