// flow-typed signature: 9db5daa185c7e44dbd2f3b229a78a39b
// flow-typed version: <<STUB>>/compression-webpack-plugin_v0.3.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compression-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compression-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'compression-webpack-plugin/index' {
  declare module.exports: $Exports<'compression-webpack-plugin'>;
}
declare module 'compression-webpack-plugin/index.js' {
  declare module.exports: $Exports<'compression-webpack-plugin'>;
}
