// flow-typed signature: f50f7e257ef87956909d3773ac3e5d7b
// flow-typed version: <<STUB>>/compression-webpack-plugin_v0.3.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compression-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'compression-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'compression-webpack-plugin/index' {
  declare module.exports: $Exports<'compression-webpack-plugin'>;
}
declare module 'compression-webpack-plugin/index.js' {
  declare module.exports: $Exports<'compression-webpack-plugin'>;
}
