// flow-typed signature: 9ed33f63b2cf35445ddb4b7eb42c510f
// flow-typed version: <<STUB>>/connect-gzip-static_v^1.0.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-gzip-static'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-gzip-static' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connect-gzip-static/lib/gzip-static' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connect-gzip-static/index' {
  declare module.exports: $Exports<'connect-gzip-static'>;
}
declare module 'connect-gzip-static/index.js' {
  declare module.exports: $Exports<'connect-gzip-static'>;
}
declare module 'connect-gzip-static/lib/gzip-static.js' {
  declare module.exports: $Exports<'connect-gzip-static/lib/gzip-static'>;
}
