// flow-typed signature: 996ebddeff9a74471666b0e4c7526a39
// flow-typed version: <<STUB>>/eslint-plugin-jsx_v^0.0.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jsx/built' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jsx/built.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx/built'>;
}
declare module 'eslint-plugin-jsx/index' {
  declare module.exports: $Exports<'eslint-plugin-jsx'>;
}
declare module 'eslint-plugin-jsx/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsx'>;
}
