// flow-typed signature: f4b96a4ebb3793cea102403e0f407864
// flow-typed version: <<STUB>>/eslint-plugin-better_v^0.1.5/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-better'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-better' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-better/rules/explicit-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-classes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-deletes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-exceptions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-exports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-fors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-function-expressions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-ifs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-imports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-instanceofs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-new' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-nulls' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-reassigns' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-switches' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-this' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-typeofs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-undefined' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-variable-declarations' {
  declare module.exports: any;
}

declare module 'eslint-plugin-better/rules/no-whiles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-better/index' {
  declare module.exports: $Exports<'eslint-plugin-better'>;
}
declare module 'eslint-plugin-better/index.js' {
  declare module.exports: $Exports<'eslint-plugin-better'>;
}
declare module 'eslint-plugin-better/rules/explicit-return.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/explicit-return'>;
}
declare module 'eslint-plugin-better/rules/no-classes.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-classes'>;
}
declare module 'eslint-plugin-better/rules/no-deletes.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-deletes'>;
}
declare module 'eslint-plugin-better/rules/no-exceptions.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-exceptions'>;
}
declare module 'eslint-plugin-better/rules/no-exports.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-exports'>;
}
declare module 'eslint-plugin-better/rules/no-fors.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-fors'>;
}
declare module 'eslint-plugin-better/rules/no-function-expressions.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-function-expressions'>;
}
declare module 'eslint-plugin-better/rules/no-ifs.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-ifs'>;
}
declare module 'eslint-plugin-better/rules/no-imports.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-imports'>;
}
declare module 'eslint-plugin-better/rules/no-instanceofs.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-instanceofs'>;
}
declare module 'eslint-plugin-better/rules/no-new.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-new'>;
}
declare module 'eslint-plugin-better/rules/no-nulls.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-nulls'>;
}
declare module 'eslint-plugin-better/rules/no-reassigns.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-reassigns'>;
}
declare module 'eslint-plugin-better/rules/no-switches.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-switches'>;
}
declare module 'eslint-plugin-better/rules/no-this.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-this'>;
}
declare module 'eslint-plugin-better/rules/no-typeofs.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-typeofs'>;
}
declare module 'eslint-plugin-better/rules/no-undefined.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-undefined'>;
}
declare module 'eslint-plugin-better/rules/no-variable-declarations.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-variable-declarations'>;
}
declare module 'eslint-plugin-better/rules/no-whiles.js' {
  declare module.exports: $Exports<'eslint-plugin-better/rules/no-whiles'>;
}
