// flow-typed signature: b7b2488ce43bd7fbe9c481fed472ebbd
// flow-typed version: <<STUB>>/express-http-proxy_v0.10.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-http-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-http-proxy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-http-proxy/lib/mockHTTP' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/bodyEncoding' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/cookies' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/decorateRequest' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/forwardPath' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/headers' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/https' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/intercept' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/middlewareCompatibility' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/port' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/session' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/status' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/timeout' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/urlParsing' {
  declare module.exports: any;
}

declare module 'express-http-proxy/test/verbs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-http-proxy/index' {
  declare module.exports: $Exports<'express-http-proxy'>;
}
declare module 'express-http-proxy/index.js' {
  declare module.exports: $Exports<'express-http-proxy'>;
}
declare module 'express-http-proxy/lib/mockHTTP.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/mockHTTP'>;
}
declare module 'express-http-proxy/test/bodyEncoding.js' {
  declare module.exports: $Exports<'express-http-proxy/test/bodyEncoding'>;
}
declare module 'express-http-proxy/test/cookies.js' {
  declare module.exports: $Exports<'express-http-proxy/test/cookies'>;
}
declare module 'express-http-proxy/test/decorateRequest.js' {
  declare module.exports: $Exports<'express-http-proxy/test/decorateRequest'>;
}
declare module 'express-http-proxy/test/forwardPath.js' {
  declare module.exports: $Exports<'express-http-proxy/test/forwardPath'>;
}
declare module 'express-http-proxy/test/headers.js' {
  declare module.exports: $Exports<'express-http-proxy/test/headers'>;
}
declare module 'express-http-proxy/test/https.js' {
  declare module.exports: $Exports<'express-http-proxy/test/https'>;
}
declare module 'express-http-proxy/test/intercept.js' {
  declare module.exports: $Exports<'express-http-proxy/test/intercept'>;
}
declare module 'express-http-proxy/test/middlewareCompatibility.js' {
  declare module.exports: $Exports<'express-http-proxy/test/middlewareCompatibility'>;
}
declare module 'express-http-proxy/test/port.js' {
  declare module.exports: $Exports<'express-http-proxy/test/port'>;
}
declare module 'express-http-proxy/test/session.js' {
  declare module.exports: $Exports<'express-http-proxy/test/session'>;
}
declare module 'express-http-proxy/test/status.js' {
  declare module.exports: $Exports<'express-http-proxy/test/status'>;
}
declare module 'express-http-proxy/test/timeout.js' {
  declare module.exports: $Exports<'express-http-proxy/test/timeout'>;
}
declare module 'express-http-proxy/test/urlParsing.js' {
  declare module.exports: $Exports<'express-http-proxy/test/urlParsing'>;
}
declare module 'express-http-proxy/test/verbs.js' {
  declare module.exports: $Exports<'express-http-proxy/test/verbs'>;
}
