// flow-typed signature: 6ffb1833a69c2724439a3cb9185e1f20
// flow-typed version: <<STUB>>/listr-verbose-renderer_v^0.5.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'listr-verbose-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'listr-verbose-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'listr-verbose-renderer/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'listr-verbose-renderer/index' {
  declare module.exports: $Exports<'listr-verbose-renderer'>;
}
declare module 'listr-verbose-renderer/index.js' {
  declare module.exports: $Exports<'listr-verbose-renderer'>;
}
declare module 'listr-verbose-renderer/lib/utils.js' {
  declare module.exports: $Exports<'listr-verbose-renderer/lib/utils'>;
}
