// flow-typed signature: 51fa624b3547929815ddd3df0563126d
// flow-typed version: <<STUB>>/listr-silent-renderer_v^1.1.1/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'listr-silent-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'listr-silent-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'listr-silent-renderer/index' {
  declare module.exports: $Exports<'listr-silent-renderer'>;
}
declare module 'listr-silent-renderer/index.js' {
  declare module.exports: $Exports<'listr-silent-renderer'>;
}
