// flow-typed signature: c95694da503e66eadfe89ecc64d49cec
// flow-typed version: <<STUB>>/listr-update-renderer_v^0.4.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'listr-update-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'listr-update-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'listr-update-renderer/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'listr-update-renderer/index' {
  declare module.exports: $Exports<'listr-update-renderer'>;
}
declare module 'listr-update-renderer/index.js' {
  declare module.exports: $Exports<'listr-update-renderer'>;
}
declare module 'listr-update-renderer/lib/utils.js' {
  declare module.exports: $Exports<'listr-update-renderer/lib/utils'>;
}
