// flow-typed signature: 5f4d5af1a6e54599e62f081977332051
// flow-typed version: <<STUB>>/multimatch_v^2.1.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multimatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multimatch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'multimatch/index' {
  declare module.exports: $Exports<'multimatch'>;
}
declare module 'multimatch/index.js' {
  declare module.exports: $Exports<'multimatch'>;
}
