// flow-typed signature: e7f803c88198e4991ad1ddd8a9df9c7d
// flow-typed version: <<STUB>>/npm-check_v5.2.3/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-check/bin/cli' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/cli' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/in/best-guess-homepage' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/in/create-package-summary' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/in/get-installed-packages' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/in/get-latest-from-registry' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/in/get-unused-packages' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/in/index' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/in/read-package-json' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/index' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/out/emoji' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/out/install-packages' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/out/interactive-update' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/out/static-output' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/state/debug' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/state/init' {
  declare module.exports: any;
}

declare module 'npm-check/lib-es5/state/state' {
  declare module.exports: any;
}

declare module 'npm-check/lib/cli' {
  declare module.exports: any;
}

declare module 'npm-check/lib/in/best-guess-homepage' {
  declare module.exports: any;
}

declare module 'npm-check/lib/in/create-package-summary' {
  declare module.exports: any;
}

declare module 'npm-check/lib/in/get-installed-packages' {
  declare module.exports: any;
}

declare module 'npm-check/lib/in/get-latest-from-registry' {
  declare module.exports: any;
}

declare module 'npm-check/lib/in/get-unused-packages' {
  declare module.exports: any;
}

declare module 'npm-check/lib/in/index' {
  declare module.exports: any;
}

declare module 'npm-check/lib/in/read-package-json' {
  declare module.exports: any;
}

declare module 'npm-check/lib/index' {
  declare module.exports: any;
}

declare module 'npm-check/lib/out/emoji' {
  declare module.exports: any;
}

declare module 'npm-check/lib/out/install-packages' {
  declare module.exports: any;
}

declare module 'npm-check/lib/out/interactive-update' {
  declare module.exports: any;
}

declare module 'npm-check/lib/out/static-output' {
  declare module.exports: any;
}

declare module 'npm-check/lib/state/debug' {
  declare module.exports: any;
}

declare module 'npm-check/lib/state/init' {
  declare module.exports: any;
}

declare module 'npm-check/lib/state/state' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-check/bin/cli.js' {
  declare module.exports: $Exports<'npm-check/bin/cli'>;
}
declare module 'npm-check/lib-es5/cli.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/cli'>;
}
declare module 'npm-check/lib-es5/in/best-guess-homepage.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/in/best-guess-homepage'>;
}
declare module 'npm-check/lib-es5/in/create-package-summary.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/in/create-package-summary'>;
}
declare module 'npm-check/lib-es5/in/get-installed-packages.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/in/get-installed-packages'>;
}
declare module 'npm-check/lib-es5/in/get-latest-from-registry.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/in/get-latest-from-registry'>;
}
declare module 'npm-check/lib-es5/in/get-unused-packages.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/in/get-unused-packages'>;
}
declare module 'npm-check/lib-es5/in/index.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/in/index'>;
}
declare module 'npm-check/lib-es5/in/read-package-json.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/in/read-package-json'>;
}
declare module 'npm-check/lib-es5/index.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/index'>;
}
declare module 'npm-check/lib-es5/out/emoji.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/out/emoji'>;
}
declare module 'npm-check/lib-es5/out/install-packages.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/out/install-packages'>;
}
declare module 'npm-check/lib-es5/out/interactive-update.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/out/interactive-update'>;
}
declare module 'npm-check/lib-es5/out/static-output.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/out/static-output'>;
}
declare module 'npm-check/lib-es5/state/debug.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/state/debug'>;
}
declare module 'npm-check/lib-es5/state/init.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/state/init'>;
}
declare module 'npm-check/lib-es5/state/state.js' {
  declare module.exports: $Exports<'npm-check/lib-es5/state/state'>;
}
declare module 'npm-check/lib/cli.js' {
  declare module.exports: $Exports<'npm-check/lib/cli'>;
}
declare module 'npm-check/lib/in/best-guess-homepage.js' {
  declare module.exports: $Exports<'npm-check/lib/in/best-guess-homepage'>;
}
declare module 'npm-check/lib/in/create-package-summary.js' {
  declare module.exports: $Exports<'npm-check/lib/in/create-package-summary'>;
}
declare module 'npm-check/lib/in/get-installed-packages.js' {
  declare module.exports: $Exports<'npm-check/lib/in/get-installed-packages'>;
}
declare module 'npm-check/lib/in/get-latest-from-registry.js' {
  declare module.exports: $Exports<'npm-check/lib/in/get-latest-from-registry'>;
}
declare module 'npm-check/lib/in/get-unused-packages.js' {
  declare module.exports: $Exports<'npm-check/lib/in/get-unused-packages'>;
}
declare module 'npm-check/lib/in/index.js' {
  declare module.exports: $Exports<'npm-check/lib/in/index'>;
}
declare module 'npm-check/lib/in/read-package-json.js' {
  declare module.exports: $Exports<'npm-check/lib/in/read-package-json'>;
}
declare module 'npm-check/lib/index.js' {
  declare module.exports: $Exports<'npm-check/lib/index'>;
}
declare module 'npm-check/lib/out/emoji.js' {
  declare module.exports: $Exports<'npm-check/lib/out/emoji'>;
}
declare module 'npm-check/lib/out/install-packages.js' {
  declare module.exports: $Exports<'npm-check/lib/out/install-packages'>;
}
declare module 'npm-check/lib/out/interactive-update.js' {
  declare module.exports: $Exports<'npm-check/lib/out/interactive-update'>;
}
declare module 'npm-check/lib/out/static-output.js' {
  declare module.exports: $Exports<'npm-check/lib/out/static-output'>;
}
declare module 'npm-check/lib/state/debug.js' {
  declare module.exports: $Exports<'npm-check/lib/state/debug'>;
}
declare module 'npm-check/lib/state/init.js' {
  declare module.exports: $Exports<'npm-check/lib/state/init'>;
}
declare module 'npm-check/lib/state/state.js' {
  declare module.exports: $Exports<'npm-check/lib/state/state'>;
}
