// flow-typed signature: 3dd04d09d82ce83621ce453430cec51b
// flow-typed version: <<STUB>>/pify_v2.3.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pify/index' {
  declare module.exports: $Exports<'pify'>;
}
declare module 'pify/index.js' {
  declare module.exports: $Exports<'pify'>;
}
