// flow-typed signature: bcc1d2c57de8441b2992f51b71f29df4
// flow-typed version: <<STUB>>/read-pkg_v2.0.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'read-pkg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'read-pkg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'read-pkg/index' {
  declare module.exports: $Exports<'read-pkg'>;
}
declare module 'read-pkg/index.js' {
  declare module.exports: $Exports<'read-pkg'>;
}
