// flow-typed signature: 1adb1e66b76bdf0a31c7a630f397b8c7
// flow-typed version: <<STUB>>/serialize-error_v^5.0.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serialize-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serialize-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'serialize-error/index' {
  declare module.exports: $Exports<'serialize-error'>;
}
declare module 'serialize-error/index.js' {
  declare module.exports: $Exports<'serialize-error'>;
}
