// flow-typed signature: 709c3cb3c00136a017e125b5a555e8ad
// flow-typed version: <<STUB>>/update-notifier_v^2.1.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'update-notifier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'update-notifier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'update-notifier/check' {
  declare module.exports: any;
}

// Filename aliases
declare module 'update-notifier/check.js' {
  declare module.exports: $Exports<'update-notifier/check'>;
}
declare module 'update-notifier/index' {
  declare module.exports: $Exports<'update-notifier'>;
}
declare module 'update-notifier/index.js' {
  declare module.exports: $Exports<'update-notifier'>;
}
