// flow-typed signature: 955df52ee585f2ce342152f40d3a010e
// flow-typed version: <<STUB>>/uppercamelcase_v^1.1.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uppercamelcase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'uppercamelcase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'uppercamelcase/index' {
  declare module.exports: $Exports<'uppercamelcase'>;
}
declare module 'uppercamelcase/index.js' {
  declare module.exports: $Exports<'uppercamelcase'>;
}
