// flow-typed signature: adcb73cc06472581a7d72faf8fd90386
// flow-typed version: <<STUB>>/write-pkg_v2.0.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'write-pkg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'write-pkg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'write-pkg/index' {
  declare module.exports: $Exports<'write-pkg'>;
}
declare module 'write-pkg/index.js' {
  declare module.exports: $Exports<'write-pkg'>;
}
