// flow-typed signature: 7b3b4d25d9663f6e24da5706b9522050
// flow-typed version: <<STUB>>/@knit/babel-preset-socks-react_vfile:src/modules/@knit/babel-preset-socks-react/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/babel-preset-socks-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/babel-preset-socks-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@knit/babel-preset-socks-react/index' {
  declare module.exports: $Exports<'@knit/babel-preset-socks-react'>;
}
declare module '@knit/babel-preset-socks-react/index.js' {
  declare module.exports: $Exports<'@knit/babel-preset-socks-react'>;
}
