// flow-typed signature: 573fb025cb5d9564201b12cbd5aa587b
// flow-typed version: <<STUB>>/@knit/common-tasks_vfile:src/packages/@knit/common-tasks/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/common-tasks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/common-tasks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/common-tasks/__tests__/tasks.test' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/copy' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/filter' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/index' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/modified' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/modules' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/preflight/git' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/preflight/ignore' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/preflight/index' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/preflight/istag' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/preflight/knit' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/preflight/version' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/public' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/read_packages' {
  declare module.exports: any;
}

declare module '@knit/common-tasks/tasks/unpublished' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/common-tasks/__tests__/tasks.test.js' {
  declare module.exports: $Exports<'@knit/common-tasks/__tests__/tasks.test'>;
}
declare module '@knit/common-tasks/index' {
  declare module.exports: $Exports<'@knit/common-tasks'>;
}
declare module '@knit/common-tasks/index.js' {
  declare module.exports: $Exports<'@knit/common-tasks'>;
}
declare module '@knit/common-tasks/tasks/copy.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/copy'>;
}
declare module '@knit/common-tasks/tasks/filter.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/filter'>;
}
declare module '@knit/common-tasks/tasks/index.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/index'>;
}
declare module '@knit/common-tasks/tasks/modified.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/modified'>;
}
declare module '@knit/common-tasks/tasks/modules.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/modules'>;
}
declare module '@knit/common-tasks/tasks/preflight/git.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/preflight/git'>;
}
declare module '@knit/common-tasks/tasks/preflight/ignore.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/preflight/ignore'>;
}
declare module '@knit/common-tasks/tasks/preflight/index.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/preflight/index'>;
}
declare module '@knit/common-tasks/tasks/preflight/istag.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/preflight/istag'>;
}
declare module '@knit/common-tasks/tasks/preflight/knit.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/preflight/knit'>;
}
declare module '@knit/common-tasks/tasks/preflight/version.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/preflight/version'>;
}
declare module '@knit/common-tasks/tasks/public.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/public'>;
}
declare module '@knit/common-tasks/tasks/read_packages.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/read_packages'>;
}
declare module '@knit/common-tasks/tasks/unpublished.js' {
  declare module.exports: $Exports<'@knit/common-tasks/tasks/unpublished'>;
}
