// flow-typed signature: 5b1df4b655945408b0ef27d6687ba971
// flow-typed version: <<STUB>>/@knit/find-dependencies_vfile:src/packages/@knit/find-dependencies/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/find-dependencies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/find-dependencies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/find-dependencies/__tests__/unit.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/find-dependencies/__tests__/unit.test.js' {
  declare module.exports: $Exports<'@knit/find-dependencies/__tests__/unit.test'>;
}
declare module '@knit/find-dependencies/index' {
  declare module.exports: $Exports<'@knit/find-dependencies'>;
}
declare module '@knit/find-dependencies/index.js' {
  declare module.exports: $Exports<'@knit/find-dependencies'>;
}
