// flow-typed signature: 70b0b61bc7ff8bb8485b35fb630c087f
// flow-typed version: <<STUB>>/@knit/find-modified-packages_vfile:src/modules/@knit/find-modified-packages/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/find-modified-packages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/find-modified-packages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/find-modified-packages/__tests__/unit.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/find-modified-packages/__tests__/unit.test.js' {
  declare module.exports: $Exports<'@knit/find-modified-packages/__tests__/unit.test'>;
}
declare module '@knit/find-modified-packages/index' {
  declare module.exports: $Exports<'@knit/find-modified-packages'>;
}
declare module '@knit/find-modified-packages/index.js' {
  declare module.exports: $Exports<'@knit/find-modified-packages'>;
}
