// flow-typed signature: 6906f7bd030905fb3b88996d75d9c79c
// flow-typed version: <<STUB>>/@knit/find-packages_vfile:src/packages/@knit/find-packages/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/find-packages'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/find-packages' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/find-packages/__tests__/unit.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/find-packages/__tests__/unit.test.js' {
  declare module.exports: $Exports<'@knit/find-packages/__tests__/unit.test'>;
}
declare module '@knit/find-packages/index' {
  declare module.exports: $Exports<'@knit/find-packages'>;
}
declare module '@knit/find-packages/index.js' {
  declare module.exports: $Exports<'@knit/find-packages'>;
}
