// flow-typed signature: db65640444442cfb18106ac79b008da1
// flow-typed version: <<STUB>>/@knit/get-package-from-dir_vfile:src/packages/@knit/get-package-from-dir/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/get-package-from-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/get-package-from-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/get-package-from-dir/__tests__/unit.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/get-package-from-dir/__tests__/unit.test.js' {
  declare module.exports: $Exports<'@knit/get-package-from-dir/__tests__/unit.test'>;
}
declare module '@knit/get-package-from-dir/index' {
  declare module.exports: $Exports<'@knit/get-package-from-dir'>;
}
declare module '@knit/get-package-from-dir/index.js' {
  declare module.exports: $Exports<'@knit/get-package-from-dir'>;
}
