// flow-typed signature: af30e69cb2a54aa9ea7deef5cae7cc76
// flow-typed version: <<STUB>>/@knit/get-package-name_vfile:src/packages/@knit/get-package-name/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/get-package-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/get-package-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/get-package-name/__tests__/unit.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/get-package-name/__tests__/unit.test.js' {
  declare module.exports: $Exports<'@knit/get-package-name/__tests__/unit.test'>;
}
declare module '@knit/get-package-name/index' {
  declare module.exports: $Exports<'@knit/get-package-name'>;
}
declare module '@knit/get-package-name/index.js' {
  declare module.exports: $Exports<'@knit/get-package-name'>;
}
