// flow-typed signature: 7bf791489b54aa4a4bc140eb81b7af0d
// flow-typed version: <<STUB>>/@knit/is-scoped_vfile:src/modules/@knit/is-scoped/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/is-scoped'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/is-scoped' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/is-scoped/__tests__/unit.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/is-scoped/__tests__/unit.test.js' {
  declare module.exports: $Exports<'@knit/is-scoped/__tests__/unit.test'>;
}
declare module '@knit/is-scoped/index' {
  declare module.exports: $Exports<'@knit/is-scoped'>;
}
declare module '@knit/is-scoped/index.js' {
  declare module.exports: $Exports<'@knit/is-scoped'>;
}
