// flow-typed signature: bd4db51801f14e8b5d496d71febf1bef
// flow-typed version: <<STUB>>/@knit/jest-config-socks_vfile:src/modules/@knit/jest-config-socks/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/jest-config-socks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/jest-config-socks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/jest-config-socks/fileMock' {
  declare module.exports: any;
}

declare module '@knit/jest-config-socks/styleMock' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/jest-config-socks/fileMock.js' {
  declare module.exports: $Exports<'@knit/jest-config-socks/fileMock'>;
}
declare module '@knit/jest-config-socks/index' {
  declare module.exports: $Exports<'@knit/jest-config-socks'>;
}
declare module '@knit/jest-config-socks/index.js' {
  declare module.exports: $Exports<'@knit/jest-config-socks'>;
}
declare module '@knit/jest-config-socks/styleMock.js' {
  declare module.exports: $Exports<'@knit/jest-config-socks/styleMock'>;
}
