// flow-typed signature: e599b1deda9b30e2c08fc6c15f5a2115
// flow-typed version: <<STUB>>/@knit/knit-core_vfile:src/packages/@knit/knit-core/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/knit-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/knit-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/knit-core/__tests__/unit.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/knit-core/__tests__/unit.test.js' {
  declare module.exports: $Exports<'@knit/knit-core/__tests__/unit.test'>;
}
declare module '@knit/knit-core/index' {
  declare module.exports: $Exports<'@knit/knit-core'>;
}
declare module '@knit/knit-core/index.js' {
  declare module.exports: $Exports<'@knit/knit-core'>;
}
