// flow-typed signature: 57296d9829d2853362932ade407b1465
// flow-typed version: <<STUB>>/@knit/knit_vfile:src/modules/@knit/knit/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/knit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/knit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/knit/bin/cli-copy' {
  declare module.exports: any;
}

declare module '@knit/knit/bin/cli-exec' {
  declare module.exports: any;
}

declare module '@knit/knit/bin/cli-list' {
  declare module.exports: any;
}

declare module '@knit/knit/bin/cli-publish' {
  declare module.exports: any;
}

declare module '@knit/knit/bin/cli-run' {
  declare module.exports: any;
}

declare module '@knit/knit/bin/cli-stitch' {
  declare module.exports: any;
}

declare module '@knit/knit/bin/cli-validate' {
  declare module.exports: any;
}

declare module '@knit/knit/bin/cli' {
  declare module.exports: any;
}

declare module '@knit/knit/tasks/exec' {
  declare module.exports: any;
}

declare module '@knit/knit/tasks/publish' {
  declare module.exports: any;
}

declare module '@knit/knit/tasks/run' {
  declare module.exports: any;
}

declare module '@knit/knit/tasks/stitch' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/knit/bin/cli-copy.js' {
  declare module.exports: $Exports<'@knit/knit/bin/cli-copy'>;
}
declare module '@knit/knit/bin/cli-exec.js' {
  declare module.exports: $Exports<'@knit/knit/bin/cli-exec'>;
}
declare module '@knit/knit/bin/cli-list.js' {
  declare module.exports: $Exports<'@knit/knit/bin/cli-list'>;
}
declare module '@knit/knit/bin/cli-publish.js' {
  declare module.exports: $Exports<'@knit/knit/bin/cli-publish'>;
}
declare module '@knit/knit/bin/cli-run.js' {
  declare module.exports: $Exports<'@knit/knit/bin/cli-run'>;
}
declare module '@knit/knit/bin/cli-stitch.js' {
  declare module.exports: $Exports<'@knit/knit/bin/cli-stitch'>;
}
declare module '@knit/knit/bin/cli-validate.js' {
  declare module.exports: $Exports<'@knit/knit/bin/cli-validate'>;
}
declare module '@knit/knit/bin/cli.js' {
  declare module.exports: $Exports<'@knit/knit/bin/cli'>;
}
declare module '@knit/knit/index' {
  declare module.exports: $Exports<'@knit/knit'>;
}
declare module '@knit/knit/index.js' {
  declare module.exports: $Exports<'@knit/knit'>;
}
declare module '@knit/knit/tasks/exec.js' {
  declare module.exports: $Exports<'@knit/knit/tasks/exec'>;
}
declare module '@knit/knit/tasks/publish.js' {
  declare module.exports: $Exports<'@knit/knit/tasks/publish'>;
}
declare module '@knit/knit/tasks/run.js' {
  declare module.exports: $Exports<'@knit/knit/tasks/run'>;
}
declare module '@knit/knit/tasks/stitch.js' {
  declare module.exports: $Exports<'@knit/knit/tasks/stitch'>;
}
