// flow-typed signature: f02713dde41238d69fd77a94ef0c2340
// flow-typed version: <<STUB>>/@knit/logger_vfile:src/packages/@knit/logger/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@knit/logger/index' {
  declare module.exports: $Exports<'@knit/logger'>;
}
declare module '@knit/logger/index.js' {
  declare module.exports: $Exports<'@knit/logger'>;
}
