// flow-typed signature: a846d5106db4d8f36b9da90bc160ed17
// flow-typed version: <<STUB>>/@knit/path-join_vfile:src/packages/@knit/path-join/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/path-join'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/path-join' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/path-join/__tests__/unit.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/path-join/__tests__/unit.test.js' {
  declare module.exports: $Exports<'@knit/path-join/__tests__/unit.test'>;
}
declare module '@knit/path-join/index' {
  declare module.exports: $Exports<'@knit/path-join'>;
}
declare module '@knit/path-join/index.js' {
  declare module.exports: $Exports<'@knit/path-join'>;
}
