// flow-typed signature: b96c76a717e0e116a8b6769f0b642960
// flow-typed version: <<STUB>>/@knit/read-pkg_vfile:src/packages/@knit/read-pkg/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/read-pkg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/read-pkg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/read-pkg/__tests__/unit.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/read-pkg/__tests__/unit.test.js' {
  declare module.exports: $Exports<'@knit/read-pkg/__tests__/unit.test'>;
}
declare module '@knit/read-pkg/index' {
  declare module.exports: $Exports<'@knit/read-pkg'>;
}
declare module '@knit/read-pkg/index.js' {
  declare module.exports: $Exports<'@knit/read-pkg'>;
}
