// flow-typed signature: de39b337a561cedbdf36555adc17f893
// flow-typed version: <<STUB>>/@knit/webpack-config-socks-lib_vfile:src/modules/@knit/webpack-config-socks-lib/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/webpack-config-socks-lib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/webpack-config-socks-lib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/webpack-config-socks-lib/production' {
  declare module.exports: any;
}

declare module '@knit/webpack-config-socks-lib/stage' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/webpack-config-socks-lib/index' {
  declare module.exports: $Exports<'@knit/webpack-config-socks-lib'>;
}
declare module '@knit/webpack-config-socks-lib/index.js' {
  declare module.exports: $Exports<'@knit/webpack-config-socks-lib'>;
}
declare module '@knit/webpack-config-socks-lib/production.js' {
  declare module.exports: $Exports<'@knit/webpack-config-socks-lib/production'>;
}
declare module '@knit/webpack-config-socks-lib/stage.js' {
  declare module.exports: $Exports<'@knit/webpack-config-socks-lib/stage'>;
}
