// flow-typed signature: c8b6b60630aa9992445bec4e6152ca6d
// flow-typed version: <<STUB>>/@knit/webpack-config-socks-app_vfile:src/modules/@knit/webpack-config-socks-app/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/webpack-config-socks-app'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/webpack-config-socks-app' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@knit/webpack-config-socks-app/production' {
  declare module.exports: any;
}

declare module '@knit/webpack-config-socks-app/stage' {
  declare module.exports: any;
}

// Filename aliases
declare module '@knit/webpack-config-socks-app/index' {
  declare module.exports: $Exports<'@knit/webpack-config-socks-app'>;
}
declare module '@knit/webpack-config-socks-app/index.js' {
  declare module.exports: $Exports<'@knit/webpack-config-socks-app'>;
}
declare module '@knit/webpack-config-socks-app/production.js' {
  declare module.exports: $Exports<'@knit/webpack-config-socks-app/production'>;
}
declare module '@knit/webpack-config-socks-app/stage.js' {
  declare module.exports: $Exports<'@knit/webpack-config-socks-app/stage'>;
}
