// flow-typed signature: e4f5fe22123d6df671e4fe270a9b8b6d
// flow-typed version: <<STUB>>/@knit/webpack-dev-server-config_vfile:src/modules/@knit/webpack-dev-server-config/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/webpack-dev-server-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/webpack-dev-server-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@knit/webpack-dev-server-config/index' {
  declare module.exports: $Exports<'@knit/webpack-dev-server-config'>;
}
declare module '@knit/webpack-dev-server-config/index.js' {
  declare module.exports: $Exports<'@knit/webpack-dev-server-config'>;
}
