// flow-typed signature: acb0dfd20b2c6b964b2aa790c455f414
// flow-typed version: <<STUB>>/@knit/yarn-utils_vfile:src/modules/@knit/yarn-utils/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@knit/yarn-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@knit/yarn-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@knit/yarn-utils/index' {
  declare module.exports: $Exports<'@knit/yarn-utils'>;
}
declare module '@knit/yarn-utils/index.js' {
  declare module.exports: $Exports<'@knit/yarn-utils'>;
}
