// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';


function isScoped($$package) {
  var b = +($$package[0] === "@");
  if (b) {
    return true;
  } else {
    return false;
  }
}

exports.isScoped = isScoped;
/* No side effect */
