name: Prerelease

on:
  push:
    branches:
      - '*'
      - '!master'
    paths:
      - '**.js*'
      - '.github/**'
      - 'src/packages/**'

env:
  KNIT_WORKING_DIR: src/packages

jobs:
  flow:
    name: Typecheck
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn problems

  lint:
    name: Linter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn lint

  validate:
    name: Validate
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: [10]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn validate

  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: [10]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test

  publish-npr:
    name: Publish NPR
    needs: [flow, lint, validate, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - name: Bump prerelease version
        run: yarn \#:prerelease
      - name: Build
        run: yarn build
      - name: Publish prerelease to registry
        run: |
          echo ${GITHUB_REF:11 | sed 's/\//-/g'}
          npm run \#:publish --tag ${GITHUB_REF:11 | sed 's/\//-/g'} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}