name: Release

on:
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  KNIT_WORKING_DIR: src/packages

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - name: Version
        run: yarn \#:release
      - name: Build
        run: yarn build
      - name: Publish
        run: yarn \#:publish