name: Release

on:
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  KNIT_WORKING_DIR: src/packages

jobs:
  publish-npr:
    name: Publish NPR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - name: Version
        run: yarn \#:release
      - name: Build
        run: yarn build
      - name: Publish
        run: npm run \#:publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}